services:
    azoo_fastapi:
        container_name: azoo_fastapi
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "9090:9090"
        depends_on:
            db:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy
        networks:
            - backend

    db:
        image: postgres:13.15
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWD}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - backend

    elasticsearch:
        container_name: azoo_elasticsearch_dev
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        environment:
            - node.name=elasticsearch
            - cluster.name=es-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-elastic}
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - TZ=Asia/Seoul  # 타임존 설정 추가
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9200/_cat/health" ]
            interval: 20s
            timeout: 10s
            retries: 3
            start_period: 10s
        networks:
            - backend

    logstash:
        container_name: azoo_logstash_dev
        build:
            context: elk/logstash
            dockerfile: Dockerfile
        volumes:
            - logstash_data:/usr/share/logstash/data
        environment:
            - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
            - TZ=Asia/Seoul  # 타임존 설정 추가
            - CONFIG_SUPPORT_ESCAPE=true
            # Database connection
            - DB_HOST=${DB_SERVER}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWD}
            # Elasticsearch connection
            - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
            - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
            - ELASTICSEARCH_USER=${ELASTICSEARCH_USER}
            - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
        networks:
            - backend
        depends_on:
            db:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy


networks:
    backend:
        driver: bridge

volumes:
    postgres-data:
    elasticsearch_data:
    logstash_data:
